# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15c81502d92df7117280bdd582c795ad58a625c2a88b74777aebb09ad57478cc9ddceefb69d5af9925859674b54944850a17e9ccfecba8a9b8c73e42aedd566a

test:
  secret_key_base: 23884c1132588288e6ad29b66f188457cbdf6e8511360a5acef4cc60226e0227f657eb75592eede825d988c817cb408fbdb4f2e84d85a5c2f8c4322290510626

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
